[package]
name = "tesla_auth"
version = "0.8.0"
description = "Tesla token generator"
homepage = "https://github.com/adriankumpf/tesla_auth"
repository = "https://github.com/adriankumpf/tesla_auth"
keywords = ["tesla-api", "oauth2", "webview", "cli"]
categories = ["command-line-utilities"]
authors = ["Adrian Kumpf"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
argh = "0.1.12"
log = "0.4.20"
muda = "0.11.2"
oauth2 = "4.4.2"
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde_json = "1.0.108"
simple_logger = { version = "4.3.0", default-features = false, features = ["stderr"] }
tao = { version = "0.24", default-features = false, features = [ "rwh_05" ] }
wry = { version = "0.35.0", default-features = false, features = ["devtools"] }

[build-dependencies]
static_vcruntime = "2.0.0"

[profile.release]
strip = "debuginfo"
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
